# Generated by Django 5.2.1 on 2025-05-18 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customsuser",
            name="username",
            field=models.CharField(
                blank=True,
                help_text="Укажите username",
                max_length=50,
                null=True,
                verbose_name="username",
            ),
        ),
    ]
