# Generated by Django 5.2.1 on 2025-05-18 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customsuser_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customsuser",
            name="username",
        ),
    ]
